"""login codes and sessions

Revision ID: 1c655be84126
Revises: b1c2d3e4f5a6
Create Date: 2026-09-13 16:26:58.366025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c655be84126'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logincode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('requested_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logincode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logincode_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_logincode_email'), ['email'], unique=False)

    op.create_table('usersession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usersession', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usersession_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_usersession_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usersession_user_id'))
        batch_op.drop_index(batch_op.f('ix_usersession_token_hash'))

    op.drop_table('usersession')
    with op.batch_alter_table('logincode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logincode_email'))
        batch_op.drop_index(batch_op.f('ix_logincode_created_at'))

    op.drop_table('logincode')
    # ### end Alembic commands ###
